language: python
python:
  - "2.7"
  - "2.6"

install:
  - ./test/setup_module_test.sh
  - pip install importlib # this is a requirement of shinken

script:
  - cd ~/shinken/test
  - export PYTHONPATH=$PYTHONPATH:~/shinken # we need shinken..
  - export PYTHONPATH=$PYTHONPATH:~/mod-livestatus/test # we also need mock_livestatus from mod-livestatus..
  - nosetests -vx --with-coverage --cover-package=module

after_success:
  coveralls

notifications:
  email: false
